### ISSUE TITLE
Meta boxes overlay content area with Gutenberg when comments are disabled (with Chrome / Chromium)

### ISSUE THREAD

**Issue by justcallmejoe** [solarissmoke/disable-comments#55] opened 2018-11-26 22:10 UTC
Please take a look at this issue report in the Gutenberg project for a detailed description and screenshot.

https://github.com/WordPress/gutenberg/issues/12270

When I disable the "Disable comments" plugin everything works as expected, so it looks there is some incompatibility of "Disable comments" with the Gutenberg editor.

**Comment by solarissmoke** [comment] 2018-11-27 04:02
Your screenshots show that you're using Yoast SEO - someone else has also reported conflicts with that particular plugin - see https://wordpress.org/support/topic/conflict-with-yoast-seo-gutenberg/ . I tried to reproduce the issue and wasn't able to, so I think there must be some specific combination of configurations that causes it.

I would repeat what I said in that thread though, that Disable Comments doesn’t do anything clever on the edit page – it doesn’t insert any scripts or styles. All it does is mark the post type as not supporting comments. If the issue is specifically with Yoast SEO then it might be worth asking them to investigate, because that plugin adds a lot of functionality to the edit page.

**Comment by justcallmejoe** [comment] 2018-11-27 22:17
Thanks for your quick answer, but I don't think Yoast SEO does matter here.

I just launched a fresh wordpress Docker container (official latest image), installed "Disable Comments" and "Gutenberg" plugins and installed "Customizr" theme, which adds a Slider meta box to the editor.

With "Disable Comments" the problem is there, without not.

![wp-gutenberg-disable-comments-bug-no-yoast-customizr](https://user-images.githubusercontent.com/45314540/49114481-9abf9e00-f298-11e8-9d7c-128779fd1c83.png)

![wp-gutenberg-disable-comments-bug-no-yoast-customizr-plugins](https://user-images.githubusercontent.com/45314540/49114487-9e532500-f298-11e8-8503-15705d2f8e51.png)

![disable-comments-settings](https://user-images.githubusercontent.com/45314540/49115061-00605a00-f29a-11e8-9cba-b2411c0ed9cd.png)

We can see an error message at the top of the page. That's the full text:

"Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/disable-comments/disable-comments.php:280) in /var/www/html/wp-includes/option.php on line 920"

I also switched back from Customizr to Twenty Fifteen theme. So there are no metaboxes, everything looks Ok. When I activate Yoast SEO now, it's metaboxes overlay the editor. In all cases this behaviour goes away, when I disable "Disable Comments". So for me clearly it must have something to do with it. Any metaboxes (either from Customizr or Yoast SEO) are messed up as soon as "Disable Comments" is activated.

I hope this helps.

**Comment by garrett-eclipse** [comment] 2018-11-27 23:30
Hi @solarissmoke I took a quick look into this and the issue is caused by Gutenberg changing how meta boxes function. Specifically when the `edit_form_advanced` action is called. 

Disable Comments uses `edit_form_advanced` and `edit_page_form` actions to hook in the `edit_form_inputs` function that injects the hidden inputs for `comment_status` and `ping_status` which causes the odd behaviour. This was raised by Yoast on the Gutenberg Project here;
https://github.com/WordPress/gutenberg/issues/10929

And appears to have been closed in favour of the commit made on 5.0 here;
https://core.trac.wordpress.org/changeset/43882

Testing this on 5.0 RC (with Gutenberg plugin removed) the issue is resolved.

I'm going to put a comment on the gutenberg issue to see if they'll merge the 5.0 code into the plugin so plugin-only users get this fix as well.

Can close this issue as it was a back-compat issue Gutenberg introduced that affected multiple plugins and has since been fixed. @justcallmejoe you can confirm by upgrading to 5.0 RC and dropping gutenberg.

**Comment by solarissmoke** [comment] 2018-11-28 02:06
@garrett-eclipse thanks a lot for digging into this!

**Closed by solarissmoke** 2018-11-28 02:06 UTC
